---
desktop_color_emoji_font_file: >-
  /usr/share/fonts/url-fonts/NotoColorEmojiBitmap/NotoColorEmoji.ttf

desktop_font_settings:
  - key: font-name
    path: /org/gnome/desktop/interface/font-name
    value: "'Noto Sans 11'"
  - key: document-font-name
    path: /org/gnome/desktop/interface/document-font-name
    value: "'Noto Sans 12'"
  - key: monospace-font-name
    path: /org/gnome/desktop/interface/monospace-font-name
    value: "'JetBrainsMono Nerd Font Mono 11'"
