---
desktop_hyper_window_tiling_uuid: hyper-window-tiling@4evy.local
desktop_hyper_window_tiling_gnome_dir: >-
  /usr/share/gnome-shell/extensions/{{ desktop_hyper_window_tiling_uuid }}
desktop_hyper_window_tiling_kwin_dir: >-
  /usr/share/kwin/scripts/hyper-window-tiling
desktop_hyper_window_tiling_gnome_keys:
  - key: move-up
    value: "['<Super><Control><Alt><Shift>w']"
  - key: move-left
    value: "['<Super><Control><Alt><Shift>a']"
  - key: move-down
    value: "['<Super><Control><Alt><Shift>s']"
  - key: move-right
    value: "['<Super><Control><Alt><Shift>d']"
  - key: move-max-almost
    value: "['<Super><Control><Alt><Shift>Return']"
  - key: move-max
    value: "['<Super><Control><Alt><Shift>backslash']"
