---
desktop_vicinae_binding_path: >-
  /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vicinae/
desktop_vicinae_command: /usr/bin/vicinae
desktop_gnome_workspace_numbers:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
