---
paths:
  .github/workflows/**/*.{yaml,yml}:
    ignore:
      - reusable workflow call "\$/.+" at "uses" is not following the format
      - specifying action "\$/.+" in invalid format because ref is missing
