---
- name: Configure repo-local C23 commands
  ansible.builtin.command:
    argv:
      - meson
      - setup
      - "{{ item.build_dir }}"
      - "--prefix={{ dotfiles_home_dir }}/.local"
    chdir: "{{ dotfiles_repo_root }}/{{ item.source_dir }}"
  environment:
    PATH: "{{ platform_homebrew_path | default(dotfiles_path) }}"
  register: tools_c_configure
  changed_when: "'Directory already configured.' not in tools_c_configure.stdout"
  loop: "{{ tools_c_tools }}"
  loop_control:
    label: "{{ item.name }}"
  when: platform_system in item.platforms
  tags:
    - repo-tools
    - c

- name: Build repo-local C23 commands
  ansible.builtin.command:
    argv:
      - meson
      - compile
      - -C
      - "{{ item.build_dir }}"
    chdir: "{{ dotfiles_repo_root }}/{{ item.source_dir }}"
  environment:
    PATH: "{{ platform_homebrew_path | default(dotfiles_path) }}"
  register: tools_c_compile
  changed_when: "'no work to do.' not in tools_c_compile.stdout"
  loop: "{{ tools_c_tools }}"
  loop_control:
    label: "{{ item.name }}"
  when: platform_system in item.platforms
  tags:
    - repo-tools
    - c

- name: Install repo-local C23 commands
  ansible.builtin.command:
    argv:
      - meson
      - install
      - -C
      - "{{ item.build_dir }}"
      - --no-rebuild
      - --only-changed
    chdir: "{{ dotfiles_repo_root }}/{{ item.source_dir }}"
  environment:
    PATH: "{{ platform_homebrew_path | default(dotfiles_path) }}"
  register: tools_c_install
  changed_when: "'Nothing to install.' not in tools_c_install.stdout"
  loop: "{{ tools_c_tools }}"
  loop_control:
    label: "{{ item.name }}"
  when: platform_system in item.platforms
  tags:
    - repo-tools
    - c
