x-fedora-image: &fedora-image
  image: localhost/dotfiles:fedora-test
  pull_policy: build
  build:
    context: .
    dockerfile: Dockerfile
    pull: true
    target: dotfiles-test
    args:
      TEST_USER: dotfiles
      TEST_UID: 1000
      TEST_GID: 1000

services:
  fedora:
    <<: *fedora-image

  fedora-shell:
    <<: *fedora-image
    profiles:
      - shell
    init: true
    stdin_open: true
    tty: true
    working_dir: /workspace/dotfiles
    command:
      - zsh
      - -l
