---
tools_homebrew_commands:
  - terminal-theme-run

tools_python_tools:
  - phone-mirror

tools_determinate_nix_installer_url: https://install.determinate.systems/nix
tools_determinate_nix_pkg_url: https://install.determinate.systems/determinate-pkg/stable/Universal
tools_determinate_nix_team_id: X3JQ4VPJZ6
tools_nix_installer_url: "{{ tools_determinate_nix_installer_url }}"
tools_nix_bin: /nix/var/nix/profiles/default/bin/nix
tools_nix_paths:
  - "{{ tools_nix_bin | dirname }}"
  - /run/current-system/sw/bin
  - "{{ dotfiles_home_dir }}/.nix-profile/bin"
  - "{{ platform_homebrew_path | default(dotfiles_path) }}"
tools_nix_path: "{{ tools_nix_paths | join(':') }}"
tools_eupkgs_flake: github:euvlok/pkgs
