---
- name: Configure RustDesk on macOS
  ansible.builtin.import_tasks: rustdesk-macos.yml
  tags:
    - rustdesk

- name: Configure Equicord on macOS
  ansible.builtin.import_tasks: equicord-macos.yml
  tags:
    - discord
    - equicord

- name: Configure Helium on macOS
  ansible.builtin.import_tasks: helium-macos.yml
  tags:
    - helium

- name: Install Raycast Beta on macOS
  ansible.builtin.import_tasks: raycast-macos.yml
  tags:
    - raycast

- name: Configure Shottr on macOS
  ansible.builtin.import_tasks: shottr-macos.yml
  tags:
    - shottr
