---
- name: Install Ghostty
  ansible.builtin.import_tasks: ghostty.yml
  when: platform_is_macos
  tags:
    - applications
    - ghostty

- name: Load private application settings
  ansible.builtin.import_tasks: private-settings.yml
  tags:
    - applications
    - helium

- name: Install Helium on Linux
  ansible.builtin.import_tasks: helium.yml
  when: platform_is_linux
  tags:
    - applications
    - helium

- name: Configure RustDesk on macOS
  ansible.builtin.import_tasks: rustdesk.yml
  when: platform_is_macos
  tags:
    - applications
    - macos
    - rustdesk

- name: Configure Helium on macOS
  ansible.builtin.import_tasks: helium.yml
  when: platform_is_macos
  tags:
    - applications
    - helium
    - macos
