---
- name: Link the RustDesk application command on macOS
  ansible.builtin.file:
    src: /Applications/RustDesk.app/Contents/MacOS/RustDesk
    dest: "{{ dotfiles_bin_dir }}/rustdesk"
    state: link
    force: true

- name: Ensure RustDesk configuration directories exist on macOS
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ dotfiles_home_dir }}/Library/Preferences/com.carriez.RustDesk"
    - "{{ dotfiles_home_dir }}/Library/LaunchAgents"

- name: Configure RustDesk direct access on macOS
  community.general.ini_file:
    path: >-
      {{ dotfiles_home_dir }}/Library/Preferences/com.carriez.RustDesk/RustDesk2.toml
    section: options
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: false
    mode: "0644"
  loop:
    - option: direct-server
      value: '"Y"'
    - option: direct-access-port
      value: '"21118"'
  loop_control:
    label: "{{ item.option }}"

- name: Install RustDesk launch agent on macOS
  ansible.builtin.copy:
    src: rustdesk/com.carriez.RustDesk.plist
    dest: "{{ dotfiles_home_dir }}/Library/LaunchAgents/com.carriez.RustDesk.plist"
    mode: "0644"
  register: applications_rustdesk_launch_agent

- name: Start the RustDesk launch agent on macOS
  community.general.launchd:
    name: com.carriez.RustDesk
    enabled: true
    state: "{{ 'restarted' if applications_rustdesk_launch_agent is changed else 'started' }}"
