---
- name: Check the Vicinae launcher
  ansible.builtin.stat:
    path: /usr/bin/vicinae
  register: applications_vicinae_command

- name: Enable and start the Vicinae launcher service
  ansible.builtin.systemd_service:
    name: vicinae.service
    enabled: true
    state: started
    scope: user
    daemon_reload: true
  when:
    - ansible_facts.service_mgr == 'systemd'
    - applications_vicinae_command.stat.executable | default(false)
