[theme]
dark = "t3_chat_dark"
light = "t3_chat_light"
fallback = "t3_chat_dark"

[editor]
auto-format = true
auto-save = false
idle-timeout = 100
completion-timeout = 50
color-modes = true
cursorline = true
line-number = "relative"
true-color = true
kitty-keyboard-protocol = "auto"
mouse = true
bufferline = "always"
completion-replace = true
completion-trigger-len = 1
text-width = 88
end-of-line-diagnostics = "hint"
popup-border = "all"
rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.gutters]
layout = ["diagnostics", "code-action-hint", "line-numbers", "spacer", "diff"]

[editor.indent-guides]
render = true

[editor.statusline]
center = ["version-control"]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-indent-style",
  "file-line-ending",
  "file-encoding",
  "file-type",
]

[editor.whitespace.characters]
nbsp = "⍽"
newline = "⏎"
space = "·"
tab = "→"
tabpad = "·"
trail = "•"

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true
auto-document-highlight = true
inlay-hints-length-limit = 50

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
git-global = true
git-ignore = true
hidden = false

[editor.file-explorer]
hidden = false
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
flatten-dirs = true

[editor.buffer-picker]
start-position = "previous"

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = true

[editor.word-completion]
enable = true
trigger-length = 4

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
"{" = "page_cursor_half_up"
"}" = "page_cursor_half_down"
G = "goto_file_end"
g = { g = "goto_file_start", q = ":reflow" }
Z = { Z = ":write-quit", Q = ":quit!" }
"space" = { "space" = "file_picker" }
C-space = "yank_to_clipboard"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
"{" = "page_cursor_half_up"
"}" = "page_cursor_half_down"
G = "goto_file_end"
g = { g = "goto_file_start", q = ":reflow" }
Z = { Z = ":write-quit", Q = ":quit!" }
C-space = "yank_to_clipboard"
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
