[[language]]
name = "python"
auto-format = true
language-servers = ["ruff"]
code-actions-on-save = ["source.organizeImports", "source.fixAll"]

[[language]]
name = "go"
language-servers = ["gopls"]

[[language]]
name = "bash"
file-types = [
  "sh",
  "bash",
  "zsh",
  { glob = "*.sh.tmpl" },
  { glob = "*.bash.tmpl" },
  { glob = "*.zsh.tmpl" },
  { glob = "dot_bash_profile.tmpl" },
  { glob = "dot_bashenv.tmpl" },
  { glob = "dot_bashrc.tmpl" },
  { glob = "dot_zshenv.tmpl" },
  { glob = "dot_zshrc.tmpl" },
]
auto-format = true
diagnostic-severity = "warning"
formatter = { command = "shfmt", args = ["-i", "2", "-bn"] }
language-servers = ["bash-language-server"]

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["typescript-language-server"]

[[language]]
name = "css"
auto-format = true
language-servers = ["vscode-css-language-server"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "rumdl", args = [
  "fmt",
  "--stdin",
  "--stdin-filename",
  "%{buffer_name}",
] }
language-servers = ["rumdl"]

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver"]

[[language]]
name = "json"
file-types = ["json", "jsonc", { glob = "*.json.tmpl" }]
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = ["vscode-json-language-server"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml", { glob = "*.yaml.tmpl" }, { glob = "*.yml.tmpl" }]
language-servers = ["yaml-language-server"]

[[language]]
name = "toml"
file-types = [
  "toml",
  { glob = "*.toml.tmpl" },
  { glob = ".chezmoiexternal.toml.tmpl" },
]
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }
language-servers = ["nil"]

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.rumdl]
command = "helix-rumdl-lsp"

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]
[language-server.ruff.config.lint]
extendSelect = ["I"]

[language-server.typescript-language-server]
command = "bunx"
args = [
  "--bun",
  "-p",
  "typescript-language-server",
  "typescript-language-server",
  "--stdio",
]
[language-server.typescript-language-server.config]
hostInfo = "helix"

[language-server.vscode-css-language-server]
command = "bunx"
args = [
  "--bun",
  "-p",
  "vscode-langservers-extracted",
  "vscode-css-language-server",
  "--stdio",
]
config = { provideFormatter = true, css = { validate = { enable = true } } }

[language-server.vscode-html-language-server]
command = "bunx"
args = [
  "--bun",
  "-p",
  "vscode-langservers-extracted",
  "vscode-html-language-server",
  "--stdio",
]
config = { provideFormatter = true }

[language-server.vscode-json-language-server]
command = "bunx"
args = [
  "--bun",
  "-p",
  "vscode-langservers-extracted",
  "vscode-json-language-server",
  "--stdio",
]
config = { provideFormatter = true, json = { validate = { enable = true } } }

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
schemaStore = { enable = true, url = "https://www.schemastore.org/api/json/catalog.json" }

[language-server.docker-langserver]
command = "bunx"
args = [
  "--bun",
  "-p",
  "dockerfile-language-server-nodejs",
  "docker-langserver",
  "--stdio",
]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]
[language-server.taplo.config.formatter]
alignEntries = true
columnWidth = 100

[language-server.nil]
command = "nil"

[language-server.just-lsp]
command = "just-lsp"
