---
applications_helium_config: >-
  {{
    lookup(
      'ansible.builtin.file',
      dotfiles_repo_root ~ '/browser/helium.toml'
    )
    | community.general.from_toml
  }}
applications_helium_linux_app_dir: >-
  {{
    applications_helium_config.browser.linux.app_dir
    | replace('${home}', dotfiles_home_dir)
    | replace('${config_home}', dotfiles_config_home)
    | replace('${data_home}', dotfiles_data_home)
  }}
