---
applications_helix_revision: >-
  {{
    lookup('env', 'HELIX_TIP_REVISION')
    | default(dotfiles_sources.helix.revision, true)
  }}
applications_helix_repository: >-
  https://github.com/{{ dotfiles_sources.helix.repository.owner }}/{{
    dotfiles_sources.helix.repository.name
  }}.git
applications_helix_cache_dir: "{{ dotfiles_cache_dir }}/helix"
applications_helix_source_dir: "{{ applications_helix_cache_dir }}/source"
applications_helix_install_prefix: "{{ dotfiles_data_dir }}/helix-tip"
applications_helix_runtime_dir: >-
  {{ applications_helix_install_prefix }}/libexec/runtime
applications_helix_executable: "{{ applications_helix_install_prefix }}/bin/hx"
