---
- name: Restart Determinate Nix daemon on macOS
  ansible.builtin.command:
    argv:
      - launchctl
      - kickstart
      - -k
      - system/systems.determinate.nix-daemon
  become: true
  changed_when: true
  listen: Restart Determinate Nix daemon
  when: platform_is_macos

- name: Restart Determinate Nix daemon on Linux
  ansible.builtin.systemd_service:
    name: nix-daemon.service
    state: restarted
  become: true
  listen: Restart Determinate Nix daemon
  when: platform_is_linux and not platform_is_nixos
