---
- name: Configure fonts
  ansible.builtin.import_tasks: fonts.yml
  when: platform_is_linux
  tags:
    - desktop
    - fonts
    - host

- name: Configure desktop settings
  ansible.builtin.import_tasks: settings.yml
  when: platform_is_linux
  tags:
    - desktop
    - host
    - vicinae

- name: Configure window tiling
  ansible.builtin.import_tasks: window-tiling.yml
  when: platform_is_linux
  tags:
    - desktop
    - host
    - hyper-window-tiling
