---
- name: Gather host service state
  ansible.builtin.service_facts:
  when: ansible_facts.service_mgr == 'systemd'

- name: Disable unused slow-boot services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    scope: system
  become: true
  loop: "{{ system_slow_boot_units }}"
  when:
    - ansible_facts.service_mgr == 'systemd'
    - item in ansible_facts.services
