---
keyboard_keep_input_remapper: >-
  {{
    lookup('ansible.builtin.env', 'DOTFILES_KEEP_INPUT_REMAPPER') == '1'
  }}

keyboard_toshy_gnome_extensions:
  - uuid: focused-window-dbus@flexagoon.com
    label: Focused Window D-Bus
  - uuid: window-calls-extended@hseliger.eu
    label: Window Calls Extended
  - uuid: xremap@k0kubun.com
    label: Xremap
