---
keyboard_toshy_render_dir: "{{ dotfiles_cache_dir }}/toshy"
keyboard_toshy_source_dir: "{{ dotfiles_cache_dir }}/sources/toshy"
keyboard_toshy_automation_dir: "{{ keyboard_toshy_render_dir }}/automation"
keyboard_toshy_config: "{{ dotfiles_config_home }}/toshy/toshy_config.py"
keyboard_toshy_slices: "{{ role_path }}/files/toshy/slices"
keyboard_toshy_merged_config: "{{ keyboard_toshy_render_dir }}/toshy_config.py"
keyboard_toshy_upstream_config: >-
  {{ keyboard_toshy_source_dir }}/default-toshy-config/toshy_config_barebones.py
keyboard_toshy_installed_revision: >-
  {{ dotfiles_data_dir }}/toshy/installed-revision
keyboard_toshy_runtime_dir: "{{ dotfiles_state_home }}/toshy/runtime"
keyboard_toshy_runtime_revision: >-
  {{ keyboard_toshy_runtime_dir }}/share/toshy/revision

keyboard_toshy_repository: >-
  https://github.com/{{ dotfiles_pins.toshy.repository.owner }}/{{
    dotfiles_pins.toshy.repository.repo
  }}.git
keyboard_toshy_revision: "{{ dotfiles_pins.toshy.revision }}"
keyboard_toshy_version: "{{ dotfiles_pins.toshy.version }}"
keyboard_toshy_force_install: >-
  {{ lookup('env', 'TOSHY_RUN_INSTALLER') == '1' }}
keyboard_toshy_distro_override: "{{ lookup('env', 'TOSHY_DISTRO_OVERRIDE') }}"
keyboard_toshy_skip_native: >-
  {{ lookup('env', 'TOSHY_SKIP_NATIVE') == '1' }}
keyboard_toshy_no_dbus_python: >-
  {{ lookup('env', 'TOSHY_NO_DBUS_PYTHON') == '1' }}
