---
name: Set Up Nix
description: Install pinned Determinate Nix.

runs:
  using: composite
  steps:
    - name: Install Determinate Nix
      uses: DeterminateSystems/determinate-nix-action@61cbfe2efc2d4e7a8a6d56967c3c1058e846c858 # v3.21.9

    - name: Cache Nix Store
      uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      with:
        use-gha-cache: enabled
        use-flakehub: disabled
