name: Bun

on:
  pull_request:
    paths: &bun-paths
      - .tool-versions
      - .github/workflows/bun.yaml
      - biome.jsonc
      - bun.lock
      - package.json
      - dotfiles/package.json
      - dotfiles/tsconfig.json
      - dotfiles/**/*.js
      - dotfiles/**/*.mjs
      - dotfiles/**/*.cjs
      - dotfiles/**/*.ts
      - packages/hyper-window-tiling/**
  push:
    paths: *bun-paths
  workflow_dispatch: null

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read # needed to checkout repository contents

jobs:
  workspace:
    name: Check JavaScript and TypeScript
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .tool-versions

      - name: Install Dependencies
        run: |
          bun install --frozen-lockfile
          bun install --cwd packages/hyper-window-tiling --frozen-lockfile

      - name: Check Workspace
        run: bun run check
