name: Check the Flake

on:
  pull_request: null
  push: null
  workflow_dispatch: null

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  linux-check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31.3.0
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
          source-url: https://install.lix.systems/lix

      - name: Run Flake Checker
        uses: DeterminateSystems/flake-checker-action@main
        with:
          check-outdated: true
          check-owner: true
          check-supported: true
          fail-mode: true
          ignore-missing-flake-lock: false

      - name: Check Linux Configuration
        run: nix flake check --show-trace

  darwin-check:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v31.3.0
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check Darwin Configuration
        run: sudo nix run nix-darwin -- check --flake .
