name: Check the Flake
'on':
  pull_request: null
  push: null
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Run Flake Checker
        uses: DeterminateSystems/flake-checker-action@main
        with:
          check-outdated: true
          check-owner: true
          check-supported: true
          fail-mode: true
          ignore-missing-flake-lock: false
      - name: Run Nix Flake Check
        run: nix flake check --show-trace
