---
name: GitHub Actions

on:
  pull_request:
    paths: &workflow-paths
      - .github/actions/**
      - .github/scripts/**
      - .github/workflows/**
  push:
    branches:
      - master
    paths: *workflow-paths
  workflow_dispatch: null

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read # needed to checkout and validate repository workflows

jobs:
  validate:
    name: Validate Workflows
    # Immutable GitHub bot IDs: Renovate, GitHub Actions, Dependabot.
    if: >-
      github.event_name != 'pull_request' ||
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) ||
      (github.event.pull_request.user.type == 'Bot' &&
      contains(fromJSON('[29139614, 41898282, 49699333]'), github.event.pull_request.user.id))
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0
        with:
          version: "1.7.12"
